[Variables]
MediaColor=255,255,255
FontSize=11
FontName=Ubuntu
FontColor=255,255,255
CoverColor=255,255,255
CoverSize=100
BarColor=255,255,255
BarDown=100
BarUp=50
PlayerPath=T:\Stuff\AIMP\aimp.exe
PlayerName=AIMP
Unit=bit/s
SColor1=255,255,255
SColor2=255,0,0
BackBarColor=255,255,255,100
Format=%I:%M %p
XColor1=255,0,0
XColor2=255,255,255

;this is where the goodies are stored
